application: isimplebin
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /download
  static_dir: download

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

  
- url: /admin
  script: admin.py

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: isimplebin.py