application: isimplebin
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: isimplebin.py