application: isimplebin
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /downloads
  static_dir: downloads

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /foobar.html
  static_files: foobar.html
  upload: foobar.html
  
- url: /admin
  script: admin.py

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
